SELECT
    m.number,
    m.sr_created_on_date,
    m.function_or_service,
    m.business_service,
    m.classification_code,
    m.resolved_by_name,
    coalesce(
        m.u_resolved_at, m.closed_at
    )                  u_resolved_at,
    m.assigned_to,
    m.assigned_to_user_name,
    m.assignment_group assignment_group,
    m.state            state,
    m.short_description,
    m.description,
    m.comments,
    m.work_notes,
    m.contact_type,
    m.close_notes,
    m.sys_class_name,
    m.priority,
    m.calendar_duration_in_days,
    m.calendar_duration_in_hours,
    m.calendar_duration_in_minutes,
    m.item form,
    m.kcs_solution,
    m.knowledge,
    m.knowledge_base,
	m.survey_response,
    m.survey_comments,
    m.resolved_by_business_unit,
    m.resolved_by_department,
    m.opened_at,
    m.opened_by_cost_center,
    m.opened_by_department,
    m.opened_by_email,
    m.opened_by_first_name,
    m.opened_by_last_name,
    m.requested_by,
    m.requested_by_cost_center,
    m.requested_by_department,
    m.requested_by_user_name,
    m.requested_for,
    m.requested_for_cost_center,
    m.requested_for_department
FROM
    support_requests.support_request m
--WHERE DESCRIPTION LIKE '%Net Investment%'
WHERE lower(DESCRIPTION) LIKE  '%commitment%'